# Generated by Django 3.0.6 on 2020-06-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0002_auto_20200603_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetracker',
            name='totalbalance',
            field=models.FloatField(default=0.0),
        ),
    ]
