# Generated by Django 3.0.6 on 2020-06-05 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0004_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetracker',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 5, 18, 30, 26, 742122)),
        ),
    ]
