# Generated by Django 3.0.6 on 2020-06-05 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0005_expensetracker_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensetracker',
            name='date',
        ),
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 5, 18, 32, 32, 590738)),
        ),
    ]
